%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Additional Functions 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function dinput = fdiff_t_syms(input,q_,dq_) 
    syms ddu1_ ddv1_ ddu2_ ddv2_ ddpsi_
    syms u1(t) v1(t) u2(t) v2(t) psi2(t) 
    syms du1(t) dv1(t) du2(t) dv2(t) dpsi(t)
    syms ddu1(t) ddv1(t) ddu2(t) ddv2(t) ddpsi(t)
    vars= [q_',...
           dq_',...
           ddu1_, ddv1_, ddu2_, ddv2_, ddpsi_];
    vars_t = [u1(t), v1(t), u2(t), v2(t), psi2(t),...
              du1(t), dv1(t), du2(t), dv2(t), dpsi(t),...
              ddu1(t), ddv1(t), ddu2(t), ddv2(t), ddpsi(t)];
          
    vars_t_end = [u1(t), v1(t), u2(t), v2(t), psi2(t),...
                  diff([u1(t), v1(t), u2(t), v2(t), psi2(t)]),...
                  du1(t), dv1(t), du2(t), dv2(t), dpsi(t),...
                  diff([du1(t), dv1(t), du2(t), dv2(t), dpsi(t)]),...
                  ddu1(t), ddv1(t), ddu2(t), ddv2(t), ddpsi(t)];
    
    vars_end = [q_',...
                dq_',...
                dq_',...
                ddu1_, ddv1_, ddu2_, ddv2_, ddpsi_,...
                ddu1_, ddv1_, ddu2_, ddv2_, ddpsi_];

    input_t = subs(input,vars,vars_t);      
    dinput_t = diff(input_t,t);
    dinput = subs(dinput_t,vars_t_end,vars_end);
end
